#!/bin/bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
mkdir -p "$ROOT/.build/module-cache"
xcrun swiftc -swift-version 5 -module-cache-path "$ROOT/.build/module-cache" "$ROOT/Sources/Models.swift" "$ROOT/Sources/ScreenFocus.swift" "$ROOT/Sources/ComputerUseActivity.swift" "$ROOT/Sources/TranscriptDecoder.swift" "$ROOT/Sources/Monitor.swift" "$ROOT/Sources/HookBridge.swift" "$ROOT/Tests/CoreTests.swift" -o "$ROOT/.build/CoreTests"
"$ROOT/.build/CoreTests"
xcrun swiftc -swift-version 5 -module-cache-path "$ROOT/.build/module-cache" "$ROOT/Sources/PetLayout.swift" "$ROOT/Tests/PetLayoutTests.swift" -o "$ROOT/.build/PetLayoutTests"
"$ROOT/.build/PetLayoutTests"
xcrun swiftc -swift-version 5 -module-cache-path "$ROOT/.build/module-cache" "$ROOT/Sources/Models.swift" "$ROOT/Sources/ScreenFocus.swift" "$ROOT/Sources/PetAnimation.swift" "$ROOT/Tests/PetAnimationTests.swift" -o "$ROOT/.build/PetAnimationTests"
"$ROOT/.build/PetAnimationTests"
xcrun swiftc -swift-version 5 -module-cache-path "$ROOT/.build/module-cache" "$ROOT/Sources/Models.swift" "$ROOT/Sources/ScreenFocus.swift" "$ROOT/Sources/PetPointerInteraction.swift" "$ROOT/Tests/InteractionTests.swift" -o "$ROOT/.build/InteractionTests"
"$ROOT/.build/InteractionTests"
python3 "$ROOT/scripts/prepare_assets.py"
xcrun swiftc -swift-version 5 -module-cache-path "$ROOT/.build/module-cache" "$ROOT/Sources/PetSpritePresentation.swift" "$ROOT/Tests/SpritePresentationTests.swift" -o "$ROOT/.build/SpritePresentationTests"
"$ROOT/.build/SpritePresentationTests" "$ROOT/.build/assets/spritesheet.png" "$ROOT/.build" "$ROOT/Resources/Pet/wave.png"
